export const projectsData = [
  {
    id: 1,
    name: "Health-Care",
    description: "create a patient healthcare to book an appointment with doctor ",
    date: "2024-08-31",
    demoLink: "https://health-care-six-beta.vercel.app/",
  },
  {
    id: 2,
    name: "Blog",
    description: "create, post and read blogs using next, quill and tailwind ",
    date: "2024-08-15",
    demoLink: "https://blog-hv0s.onrender.com/",
  },
  {
    id: 3,
    name: "E-Commerse",
    description: "Track your carbon footprint",
    date: "2022-08-15",
    demoLink: "https://classy-banoffee-143f01.netlify.app/",
  },
  {
    id: 4,
    name: "Image Editor",
    description: "users can use image link, and can modify there images",
    date: "2022-06-20",
    demoLink: "https://cozy-kitsune-a35ae8.netlify.app/",
  },
  {
    id: 5,
    name: "JavaScript Compiler",
    description: "HTML, CSS and JS code editor",
    date: "2022-09-10",
    demoLink: "https://dashing-quokka-d9f592.netlify.app/",
  },
  {
    id: 6,
    name: "BookStore",
    description: "Read whatever books you wanted to read.",
    date: "2022-05-30",
    demoLink: "https://deluxe-lamington-54d9e8.netlify.app/",
  },
  {
    id: 7,
    name: "TRAVEL & TOUR",
    description: "Discover and Enjoy tourist package in buget",
    date: "2022-07-12",
    demoLink: "https://melodic-crepe-2fd7c5.netlify.app/",
  },
  {
    id: 8,
    name: "ToDo List",
    description: "Write your plan",
    date: "2022-10-01",
    demoLink: "https://voluble-donut-06d9d1.netlify.app/",
  },
  {
    id: 9,
    name: "Admin Dashboard",
    description: "Display key performance indicators and metrics.",
    date: "2022-04-18",
    demoLink: "https://unique-marshmallow-bcde31.netlify.app/",
  },
  {
    id: 10,
    name: "Movie Watchlist",
    description: "Search movie and add it in your watchlist",
    date: "2022-11-05",
    demoLink: "https://authenticate-react-movie-app.netlify.app/",
  },
  {
    id: 11,
    name: "Timeline",
    description: "A simple timeline of mine",
    date: "2022-03-22",
    demoLink: "https://melodious-custard-cfc573.netlify.app/",
  },
  {
    id: 12,
    name: "GAME OF THRONES",
    description: "POPULAR CHARACTER",
    date: "2022-02-14",
    demoLink: "https://thunderous-crumble-3e6925.netlify.app/",
  },
];

export const BtnList = [
  { label: "Home", link: "/", icon: "home", newTab: false },
  { label: "About", link: "/about", icon: "about", newTab: false },
  { label: "Projects", link: "/projects", icon: "projects", newTab: false },
  { label: "Contact", link: "/contact", icon: "contact", newTab: false },
  {
    label: "Github",
    link: "https://github.com/animeshkumar7717",
    icon: "github",
    newTab: true,
  },
  {
    label: "LinkedIn",
    link: "https://www.linkedin.com/in/animeshkumar77/",
    icon: "linkedin",
    newTab: true,
  },
  {
    label: "X",
    link: "https://twitter.com/anim1826",
    icon: "twitter",
    newTab: true,
  },
  {
    label: "Resume",
    link: "/animesh-resume.pdf",
    icon: "resume",
    newTab: true,
  },
];

